# Project: tree
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o
LINKOBJ  = Main.o
LIBS     = -L"J:/programSoft/Dev-Cpp/MinGW64/lib" -L"J:/programSoft/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"J:/programSoft/Dev-Cpp/MinGW64/include" -I"J:/programSoft/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"J:/programSoft/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"J:/programSoft/Dev-Cpp/MinGW64/include" -I"J:/programSoft/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"J:/programSoft/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"J:/programSoft/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = tree.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)
